config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  post '/posts/:id' => 'posts#twilio'
  post '/location' => 'users#location'
  get '/logout' => 'users#logout'
  get'/thanks' => 'posts#thanks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates_presence_of :phone_number, :title, :description, :location
  mount_uploader :image, ImageUploader

  def latlng
    address = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{self.location}&key=#{ENV.fetch('MAP_KEY')}").parsed_response
    self.lat = address["results"][0]["geometry"]["location"]["lat"]
    self.lng = address["results"][0]["geometry"]["location"]["lng"]
    self.save
  end

  # there's probably a function to do this in Math
  # but I'm just lazy
  def radians(deg)
    deg * Math::PI / 180
  end

  def lat_radians
    radians(lat.to_f)
  end

  def lng_radians
    radians(lng.to_f)
  end

  EARTH_RADIUS = 3958.756; # in miles
  def distance_from(lat, lng)
    return 0 if lat.nil? || lng.nil?
    lat_radians = radians(lat)
    lng_radians = radians(lng)

    dist_lat = lat_radians - self.lat_radians
    dist_long = lng_radians - self.lng_radians

    a =  (Math.sin(dist_long/2))**2 +
        Math.cos(self.lat_radians) *
        Math.cos(lat_radians) *
        (Math.sin(dist_long/2))**2
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))
    EARTH_RADIUS * c
  end
end

app/models/twilio_api.rb
class TwilioApi
  SID = ENV.fetch('TWILIO_ACCOUNT_SID')
  TOKEN = ENV.fetch('TWILIO_AUTH_TOKEN')
  CLIENT = Twilio::REST::Client.new(SID, TOKEN)

  def self.twilio_number
    # A Twilio number you control - choose one from:
    # https://www.twilio.com/user/account/phone-numbers/incoming
    # Specify in E.164 format, e.g. "+16519998877"
    ENV['TWILIO_NUMBER']
  end

  def self.send(opts = {})
    CLIENT.account.messages.create(
      from:  opts[:from],
      to:    opts[:to],
      body:  opts[:body]
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  private

  # def are_you_new?
  #   # this_id = request.session_options[:id]
  #   # @current_user = User.find_or_create_by(session_id: this_id)
  #   # current_user
  # end

  def current_user
    @current_user ||= if session.id
      User.find_or_create_by!(session_id: session.id)
    else
      reset_session
      User.find_or_create_by!(session_id: session.id)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  after_action :latlng, only: [:create, :update]


  # GET /posts
  # GET /posts.json
  def index
    @page = params[:page].to_i || 1
    skip = (@page) * 9
    @posts = Post.all.order(created_at: :desc).limit(9).offset(skip)

    lat = session[:lat]
    lng = session[:lng]
    if lat and lng
      @posts = @posts.sort_by do |post|
        post.distance_from(lat, lng)
      end
    end
  end

  def thanks
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Alright! Your post was successfully created!' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def twilio
    TwilioApi.send(
      from:  ENV.fetch('TWILIO_NUMBER'),
      to:    agent_number,
      body:  message
    )
    redirect_to '/thanks'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def latlng
      @post.latlng
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :location, :tag, :price, :user_id, :phone_number)
    end
    # def post_params
    #   params.require(:post).permit(:title, :content, :image)
    # end

    def message
      # byebug
      "Hey! Looks like someone is interested in  #{params[:hidden_title]}. " \
      "You can contact them back at:  #{params[:phone_number]}. " \
      "Message: #{params[:message]}"
    end

    def agent_number
      # The sales rep / agent's phone number
      set_post
      agent_number =  @post.phone_number #ENV['AGENT_NUMBER']

    end

    def sort_time
      @page = params[:page].to_i || 1
      skip = (@page) * 9
      @posts = Post.all.order(created_at: :desc).limit(9).offset(skip)
    end

    def self.sort_distance
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def location
    lat, lng = params[:lat], params[:lng]
    session[:lat] = lat.to_f
    session[:lng] = lng.to_f
  end

  def logout
    reset_session
    render json: session
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:session_id, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Free For All</title>
    <%= csrf_meta_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC|Amaranth|Baloo+Chettan|Dorsa|Julius+Sans+One|Meera+Inimai|Monoton|Montserrat+Alternates|Mukta+Vaani|Pattaya|Rochester|Sue+Ellen+Francisco|Unica+One|Vibur" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-twitch" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<span class="small-nav"> <span class="logo"> &lt;FFA&gt; </span> </span>
				<span class="full-nav"> &lt; Bootsnipp &gt; </span>
			</a>
		</div>
		<div class="">
			<ul class="nav navbar-nav">
				<li class="active">

					<a href="/">
						<span class="small-nav" data-toggle="tooltip" data-placement="right" title="Home" data-original-title="Home">
							<span class="glyphicon glyphicon-home"></span>
						</span>
						<span class="full-nav"> Home </span>
					</a>
				</li>
				<li>
					<a href="/posts/new">
						<span class="small-nav" data-toggle="tooltip" data-placement="right" title="Create Post" data-original-title="Contact Us">
							<span class="fa fa-plus-circle"></span>
						</span>
						<span class="full-nav"> New Post </span>
					</a>
				</li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :title %></p>
    <%= form.text_field :title, id: :post_title, :size => 50 %>
  </div><br><br>

  <div class="field">
    <p><strong><%= form.label :description %></strong></p>
    <%= form.text_area :description, id: :post_description, cols: 50, rows: 10 %>
  </div><br><br>

  <div class="field">
    <p><strong>add an image....</strong></p>
    <%= form.file_field :image %>
  </div><br><br>

  <div class="field">
    <p><%= form.label :location %> Address of where your item is located</p>
    <%= form.text_field :location, id: :post_location, :size => 50 %>
  </div><br><br>
  <!-- <div class="field">
    <p><%= form.label :tag %></p>
    <%= form.text_field :tag, id: :post_tag, :size => 50 %>
  </div> -->

  <!-- <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :post_price %>
  </div> -->


    <%= form.hidden_field :user_id, id: :post_user_id, :value => @current_user.id  %>


  <%# user_id = @current_user%>
<!-- User.find(session_id: request.session_options[:id])  -->
<%# form.text_field :, :value => @make_id %>
  <div class="field">
    <p><%= form.label :phone_number %></p>
    <%= form.text_field :phone_number, id: :post_phone_number, :size => 50%>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<!-- <button><%= link_to 'New Post', new_post_path %></button> -->
<section class="module parallax parallax-1">
  <div class="container">
      <h1><strong><span id="free">free</span></strong> <span id="for">for</span><strong><span id="all"> all</span></strong></h1>
      <h4>A place to post and explore <span>treasures</span> </h4>
    </div>
  </section>

<section class="module content">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <h1>Recent Posts</h1><br>
      <% @posts.each do |post| %>
      <div id="items">
        <div> Posted <span id="time"><%= time_ago_in_words(post.created_at) %> ago</span></div><br>
        <div id='center'><strong> <%= post.title %></strong></div><hr>
        <div id="section"><strong>Description: </strong><br><%= raw (post.description).truncate(50) %></div><br><br><br><br>
        <div id="section"><strong>Distance: </strong><br><span id="miles"><%= post.distance_from(session[:lat], session[:lng]).round(1) %> miles away</span></div><br>
        <% unless post.image.to_s.empty? %>
        <div id="img-section"><strong>Image: </strong><div id='img-here'> <%= image_tag post.image %> </div><br>
        <% else %>
        <div id="img-section"><strong>Image: </strong><div id="img-none"> <strong>N/A </strong></div><br>
        <% end %>

      </div><br><br><br><br>

      <!-- <div><strong>Phone Number: </strong><%= post.phone_number %></div> -->
      <div id="deets"><strong></strong><%= link_to 'More details...', post %></div>
    </div>
    <% end %><br><br><br>
    <div id="link">
      <button type="button" class="btn btn-outline-info">
        <%= link_to 'Previous Page', page: @page - 1 %></button> &nbsp;
        <button type="button" class="btn btn-outline-info">
          <%= link_to 'Next Page', page: @page + 1 %></button>
        </div>
      </div>
    </div>
  </section>

<br>

app/views/posts/new.html.erb
<section class="new-module parallax parallax-1">
  <div class="container">
    <h1><strong>New Post</strong></h1>
  </div>
</section>

<section class="module content">
  <div class="container">

    <div class="new-from"><%= render 'form', post: @post %></div>

  </div>
</section>
<!-- <button class="form-back"><%= link_to 'Back', posts_path %></button> -->

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="bck-btn"><button type="button" class="btn btn-outline-primary"><%= link_to 'Back', posts_path %></button></div><br><br><br><br>

  <!-- <strong>Title:</strong> -->
  <div class="post-title"><strong><%= @post.title %></strong></div>
</p><br>



<p>
  <div class="post-image">
  <!-- <strong>Image:</strong><br> -->
  <%= image_tag @post.image_url.to_s %>
</div>
</p>

</p>

<div class="map-stuff">
<!-- start map -->
<% the_source ="https://maps.googleapis.com/maps/api/staticmap?
center=#{@post.location}&zoom=14&size=550x425
&markers=icon:https://goo.gl/1oTJ9Y%7C#{@post.location}
&key=AIzaSyDjlbo60sptFY4BnIpEVTlWFU3TCq-nNII" %>
<%= image_tag the_source, :class => "mape"%>

<!-- end map -->
<p>
  <div class="post-location"><strong>Item Location:</strong>
  <%= @post.distance_from(session[:lat], session[:lng]).round(1) %> miles away</div>

</p>

<iframe src="https://www.facebook.com/plugins/share_button.php?href=http%3A%2F%2Flocalhost%3A3000%2Fposts%2F:id&layout=button&size=small&mobile_iframe=true&appId=312251409194916&width=59&height=20" width="59" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>

</div>


<p>
  <!-- <strong>Description:</strong> -->
  <div class="post-description"><%= @post.description %></div>
</p>

<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>

<!-- <div id="edit"><%= link_to 'Edit Post', edit_post_path(@post) %> </div> -->
<br><br><br>

<hr>







<div id="contact-poster">
<p>Contact the poster of: &nbsp;<strong><%= @post.title %></strong></p><br><br>
<%= form_tag(post_path, method: "post") do %>
<input type="hidden" name="hidden_title" value="<%= @post.title %>" /><br>
  <div class="show-field"><%= label_tag(:phone_number, "Phone number:") %>
  <%= text_field_tag (:phone_number) %></div>
  <div class="show-field"><%= label_tag(:message, "Message:") %>
  <%= text_area_tag(:message) %><br></div>
  <div class="show-submit"><%= submit_tag("Contact") %> </div>

<% end %>
</div>








<!-- <button type="button" onclick="sendTextMessage()"> Send Message </button> -->

app/views/posts/thanks.html.erb
<div class="thanks"><h1>thanks for your message!</h1></div>
<div class="banana"><img src="https://img.clipartfest.com/65942d6adbdfae9764420a3087ffcd2d_hooray-clip-art-gallery-hooray-clipart_300-276.png" alt="nana"></div>
<div class="thanks"><h4> The poster will be in contact with you shortly via text</h4></div>



<div class="back"><button type="button" class="btn btn-info"><%= link_to 'Back to Posts', root_path %></button></div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :session_id %>
    <%= form.text_field :session_id, id: :user_session_id %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :user_phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Session</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.session_id %></td>
        <td><%= user.phone_number %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Session:</strong>
  <%= @user.session_id %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>